'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewPayment

    '''<summary>
    '''msgdiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inputdiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NewPaymentForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewPaymentForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''mid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mid As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pid As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''amt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''famt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents famt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vfrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vfrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pmode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pmode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txnno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txnno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trainer As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnAddPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPayment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''processdiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents processdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''memid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''payid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents payid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''duration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents duration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''famount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents famount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''validfrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validfrom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''validtill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validtill As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''paymode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ptrainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ptrainer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''colby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents colby As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnpayfinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnpayfinal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btncanceltxn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncanceltxn As Global.System.Web.UI.WebControls.Button
End Class
